#  Makefile for GNU Emacs lib-src directory.
#   Geoff Voelker (voelker@cs.washington.edu)
#  Copyright (C) 1994 Free Software Foundation, Inc.
#
#  This file is part of GNU Emacs.
#  
#  GNU Emacs is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#  
#  GNU Emacs is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with GNU Emacs; see the file COPYING.  If not, write to the
#  Free Software Foundation, Inc., 59 Temple Place - Suite 330,
#  Boston, MA 02111-1307, USA.
#

# 
# Sets up the system dependent macros.
#
!include ..\nt\makefile.def

LOCAL_FLAGS	= -DWINDOWSNT -DDOS_NT -DSTDC_HEADERS=1 -DNO_LDAV=1 \
	-DNO_ARCHIVES=1 -DHAVE_CONFIG_H=1 -I..\nt\inc -I..\src

LINK_FLAGS	= $(ARCH_LDFLAGS) -debug:PARTIAL -machine:$(ARCH) -subsystem:console -entry:mainCRTStartup setargv.obj

ALL	        = $(BLD)\make-docfile.exe \
		$(BLD)\hexl.exe		\
		$(BLD)\ctags.exe	\
		$(BLD)\etags.exe	\
		$(BLD)\ebrowse.exe	\
		$(BLD)\movemail.exe


# don't know what (if) to do with these yet...
#
#		$(BLD)\sorted-doc.exe	\
#		$(BLD)\env.exe		\
#		$(BLD)\server.exe	\
#		$(BLD)\emacstool.exe	\
#		$(BLD)\leditcfns.exe	\
#		$(BLD)\emacsclient.exe	\
#		$(BLD)\cvtmail.exe	\
#		$(BLD)\digest-doc.exe	\
#		$(BLD)\test-distrib.exe	\


LIBS	      = $(BASE_LIBS)

$(BLD)\make-docfile.exe: 	$(BLD)\make-docfile.obj $(BLD)\ntlib.obj
		$(LINK) -out:$@ $(LINK_FLAGS) $(BLD)\make-docfile.obj $(BLD)\ntlib.obj $(LIBS)
$(BLD)\hexl.exe:		$(BLD)\hexl.obj
$(BLD)\fakemail.exe: 		$(BLD)\fakemail.obj $(BLD)\ntlib.obj
		$(LINK) -out:$@ $(LINK_FLAGS) -debug:full $(BLD)\fakemail.obj $(BLD)\ntlib.obj $(LIBS)

make-docfile:	$(BLD) $(BLD)\make-docfile.exe
etags:		$(BLD) $(BLD)\etags.exe
ebrowse:	$(BLD) $(BLD)\ebrowse.exe
hexl:		$(BLD) $(BLD)\hexl.exe
movemail:	$(BLD) $(BLD)\movemail.exe
fakemail:	$(BLD) $(BLD)\fakemail.exe

GETOPTOBJS = $(BLD)\getopt.obj $(BLD)\getopt1.obj
GETOPTDEPS = $(GETOPTOBJS) getopt.h
MOVEMAILOBJS =  $(BLD)\movemail.obj \
		$(BLD)\pop.obj \
		$(BLD)\md5.obj \
		$(BLD)\ntlib.obj \
		$(GETOPTOBJS)

MOVEMAIL_PROGDLG = $(BLD)\progdlg.obj \
		   $(BLD)\progdlg.res

MOVEMAIL_PROGDLG_LIB = comctl32.lib user32.lib

$(BLD)\movemail.exe:	$(MOVEMAILOBJS) $(MOVEMAIL_PROGDLG) getopt.h
# put wsock32.lib before $(LIBS) to ensure we don't link to ws2_32.lib
		$(LINK) -out:$@ $(LINK_FLAGS) -debug:FULL \
                        $(MOVEMAILOBJS) $(MOVEMAIL_PROGDLG) \
                        wsock32.lib $(LIBS) $(MOVEMAIL_PROGDLG_LIB)

ETAGSOBJ      = $(BLD)\etags.obj \
		$(BLD)\getopt.obj \
		$(BLD)\getopt1.obj \
		$(BLD)\ntlib.obj \
		$(BLD)\regex.obj


$(BLD)\etags.exe: 	$(ETAGSOBJ)
		$(LINK) -out:$@ $(LINK_FLAGS) $(ETAGSOBJ) $(LIBS)


$(BLD)\regex.obj: ../src/regex.c ../src/regex.h ../src/config.h
		$(CC)  $(CFLAGS) -DCONFIG_BROKETS -DINHIBIT_STRING_HEADER \
		../src/regex.c -Fo$@

ETAGS_CFLAGS  = -DHAVE_GETCWD
$(BLD)\etags.obj: etags.c
		$(CC) $(CFLAGS) $(ETAGS_CFLAGS) -Fo$@ etags.c

CTAGSOBJ      = $(BLD)\ctags.obj \
		$(BLD)\getopt.obj \
		$(BLD)\getopt1.obj \
		$(BLD)\ntlib.obj \
		$(BLD)\regex.obj

$(BLD)\ctags.exe:           ctags.c $(CTAGSOBJ)
		$(LINK) -out:$@ $(LINK_FLAGS) $(CTAGSOBJ) $(LIBS)

ctags.c:	etags.c
		- $(DEL) ctags.c
		copy etags.c ctags.c

CTAGS_CFLAGS  = -DCTAGS $(ETAGS_CFLAGS)
$(BLD)\ctags.obj: ctags.c
		$(CC) $(CFLAGS) $(CTAGS_CFLAGS) -Fo$@ ctags.c

EBROWSE_OBJ   = $(BLD)\ebrowse.obj \
		$(BLD)\getopt.obj \
		$(BLD)\getopt1.obj \
		$(BLD)\ntlib.obj

$(BLD)\ebrowse.exe:	$(EBROWSE_OBJ)
		$(LINK) -out:$@ $(LINK_FLAGS) $(EBROWSE_OBJ) $(LIBS)

$(BLD)\ebrowse.obj: ebrowse.c ..\src\config.h
		$(CC) $(CFLAGS) -DVERSION=\"$(VERSION)\" -Fo$@ ebrowse.c
#
# don't know what to do with these yet...
#
# $(BLD)\sorted-doc.exe: 	$(BLD)\sorted-doc.obj
# $(BLD)\yow.exe: 		$(BLD)\yow.obj
# $(BLD)\emacstool.exe: 	$(BLD)\emacstool.obj
# $(BLD)\leditcfns.exe: 	$(BLD)\leditcfns.obj
# $(BLD)\server.exe: 		$(BLD)\server.obj
# $(BLD)\cvtmail.exe: 		$(BLD)\cvtmail.obj
# $(BLD)\digest-doc.exe: 	$(BLD)\digest-doc.obj
# $(BLD)\emacsclient.exe: 	$(BLD)\emacsclient.obj
# $(BLD)\test-distrib.exe: 	$(BLD)\test-distrib.obj

#
# From ..\src\makefile.nt.
#
objsource = ../src/
obj = \
	$(objsource)abbrev.c \
	$(objsource)alloc.c \
	$(objsource)alloca.c \
	$(objsource)buffer.c \
	$(objsource)bytecode.c \
	$(objsource)callint.c \
	$(objsource)callproc.c \
	$(objsource)casefiddle.c \
	$(objsource)casetab.c \
	$(objsource)category.c \
	$(objsource)ccl.c \
	$(objsource)charset.c \
	$(objsource)cm.c \
	$(objsource)cmds.c \
	$(objsource)coding.c \
	$(objsource)composite.c \
	$(objsource)data.c \
	$(objsource)dired.c \
	$(objsource)dispnew.c \
	$(objsource)doc.c \
	$(objsource)doprnt.c \
	$(objsource)editfns.c \
	$(objsource)emacs.c \
	$(objsource)eval.c \
	$(objsource)fileio.c \
	$(objsource)filelock.c \
	$(objsource)filemode.c \
	$(objsource)firstfile.c \
	$(objsource)floatfns.c \
	$(objsource)fns.c \
	$(objsource)fontset.c \
	$(objsource)frame.c \
	$(objsource)gmalloc.c \
	$(objsource)indent.c \
	$(objsource)insdel.c \
	$(objsource)intervals.c \
	$(objsource)keyboard.c \
	$(objsource)keymap.c \
	$(objsource)lastfile.c \
	$(objsource)lread.c \
	$(objsource)macros.c \
	$(objsource)marker.c \
	$(objsource)md5.c \
	$(objsource)minibuf.c \
	$(objsource)mocklisp.c \
	$(objsource)mw32atimer.c \
	$(objsource)mw32bdf.c \
	$(objsource)mw32clpbd.c \
	$(objsource)mw32dl.c \
	$(objsource)mw32fns.c \
	$(objsource)mw32font.c \
	$(objsource)mw32ime.c \
	$(objsource)mw32mci.c \
	$(objsource)mw32mem.c \
	$(objsource)mw32menu.c \
	$(objsource)mw32reg.c \
	$(objsource)mw32term.c \
	$(objsource)print.c \
	$(objsource)process.c \
	$(objsource)ralloc.c \
	$(objsource)regex.c \
	$(objsource)region-cache.c \
	$(objsource)scroll.c \
	$(objsource)search.c \
	$(objsource)strftime.c \
	$(objsource)syntax.c \
	$(objsource)sysdep.c \
	$(objsource)term.c \
	$(objsource)termcap.c \
	$(objsource)textprop.c \
	$(objsource)tparam.c \
	$(objsource)undo.c \
	$(objsource)vm-limit.c \
	$(objsource)w32.c \
	$(objsource)w32console.c \
	$(objsource)w32inevt.c \
	$(objsource)w32proc.c \
	$(objsource)window.c \
	$(objsource)xdisp.c \
	$(objsource)xfaces.c

#
# These are the lisp files that are loaded up in loadup.el
#
lispsource = ../lisp/

FACE_SUPPORT = $(lispsource)facemenu.elc
!if $(MEADOW)
MOUSE_SUPPORT = $(lispsource)select.elc
!else
MOUSE_SUPPORT = $(lispsource)select.elc $(lispsource)scroll-bar.elc $(lispsource)mouse.elc
!endif
FLOAT_SUPPORT = $(lispsource)float-sup.elc

!if $(MEADOW)
WINNT_SUPPORT = $(lispsource)ls-lisp.elc $(lispsource)w32-fns.elc \
		$(lispsource)dos-w32.elc $(lispsource)disp-table.elc \
		$(lispsource)mw32faces.elc $(lispsource)mw32scroll.elc \
		$(lispsource)international/mw32misc.elc \
		$(lispsource)international/mw32mci.elc \
		$(lispsource)international/meadow.elc
!else
WINNT_SUPPORT = $(lispsource)ls-lisp.elc $(lispsource)w32-fns.elc $(lispsource)dos-w32.elc
!endif

lisp= \
	$(lispsource)abbrev.elc \
	$(lispsource)buff-menu.elc \
	$(lispsource)byte-run.elc \
	$(lispsource)cus-start.el \
	$(lispsource)custom.elc \
!if !$(MEADOW)
	$(lispsource)disp-table.elc \
	$(lispsource)faces.elc \
!endif
	$(lispsource)files.elc \
	$(lispsource)textmodes/fill.elc \
	$(lispsource)format.elc \
	$(FACE_SUPPORT) \
	$(MOUSE_SUPPORT) \
	$(FLOAT_SUPPORT) \
	$(lispsource)frame.elc\
	$(X_WINDOWS_SUPPORT) \
	$(lispsource)help.elc \
	$(lispsource)indent.elc \
	$(lispsource)isearch.elc \
	$(lispsource)emacs-lisp/lisp-mode.elc \
	$(lispsource)emacs-lisp/lisp.elc \
	$(lispsource)loadup.el \
	$(lispsource)loaddefs.el \
	$(lispsource)bindings.el \
	$(lispsource)map-ynp.elc \
	$(lispsource)menu-bar.elc \
	$(lispsource)international/mule.elc \
	$(lispsource)international/mule-conf.el \
	$(lispsource)international/mule-cmds.elc \
	$(lispsource)international/characters.elc \
	$(lispsource)international/ccl.elc \
	$(lispsource)international/codepage.elc \
	$(lispsource)international/utf-8.elc \
	$(lispsource)case-table.elc \
	$(lispsource)language/chinese.elc \
	$(lispsource)language/cyrillic.elc \
	$(lispsource)language/devanagari.el \
	$(lispsource)language/english.el \
	$(lispsource)language/ethiopic.el \
	$(lispsource)language/european.el \
	$(lispsource)language/czech.el \
	$(lispsource)language/slovak.el \
	$(lispsource)language/romanian.el \
	$(lispsource)language/greek.el \
	$(lispsource)language/hebrew.el \
	$(lispsource)language/indian.el \
	$(lispsource)language/japanese.el \
	$(lispsource)language/korean.el \
	$(lispsource)language/lao.el \
	$(lispsource)language/thai.el \
	$(lispsource)language/tibetan.el \
	$(lispsource)language/vietnamese.el \
	$(lispsource)language/misc-lang.el \
	$(lispsource)textmodes/page.elc \
	$(lispsource)textmodes/paragraphs.elc \
	$(lispsource)paths.el \
	$(lispsource)register.elc \
	$(lispsource)replace.elc \
	$(lispsource)simple.elc \
	$(lispsource)startup.elc \
	$(lispsource)subr.elc \
	$(lispsource)term/tty-colors.elc \
	$(lispsource)textmodes/text-mode.elc \
	$(lispsource)vc-hooks.elc \
	$(lispsource)ediff-hook.elc \
	$(VMS_SUPPORT) \
	$(MSDOS_SUPPORT) \
	$(WINNT_SUPPORT) \
	$(lispsource)widget.elc \
	$(lispsource)window.elc \
	$(lispsource)version.el


DOC	      = DOC 
$(DOC):		$(BLD)\make-docfile.exe $(obj) $(lisp)
		- $(DEL) $(DOC)
		$(BLD)\make-docfile -d ..\src $(obj) > $(DOC)
		$(BLD)\make-docfile -d ..\src $(lisp) >> $(DOC)
		$(CP) $(DOC) ..\etc\DOC-X
		- mkdir ..\src\$(OBJDIR)
		- mkdir ..\src\$(OBJDIR)\etc
		$(CP) $(DOC) ..\src\$(OBJDIR)\etc\DOC-X

{$(BLD)}.obj{$(BLD)}.exe:
		$(LINK) -out:$@ $(LINK_FLAGS) $*.obj $(LIBS)

!IF "$(_NMAKE_VER)" != "$(_NMAKE_VER_4)" && "$(ARCH)" == "i386"
.c{$(BLD)}.obj::
		$(CC) $(CFLAGS) -Fo$(BLD)\ $<
!ELSE
.c{$(BLD)}.obj:
		$(CC) $(CFLAGS) -Fo$@ $<
!ENDIF

#
# Build the executables
#
all:		$(BLD) $(ALL) $(DOC)

#
# Assuming INSTALL_DIR is defined, build and install emacs in it.
#
INSTALL_FILES = $(ALL)
install:	$(INSTALL_FILES)
		- mkdir $(INSTALL_DIR)\bin
		$(CP) $(BLD)\etags.exe $(INSTALL_DIR)\bin
		$(CP) $(BLD)\ctags.exe $(INSTALL_DIR)\bin
		$(CP) $(BLD)\hexl.exe $(INSTALL_DIR)\bin
		$(CP) $(BLD)\movemail.exe $(INSTALL_DIR)\bin
		- mkdir $(INSTALL_DIR)\etc
		$(CP) $(DOC) $(INSTALL_DIR)\etc

# Don't install fakemail by default. It sends mail into a
# blackhole if /bin/mail is not installed.
#		$(CP) $(BLD)\fakemail.exe $(INSTALL_DIR)\bin

#
# Maintenance
# 
clean:;		- $(DEL) *~ *.pdb DOC*
		- $(DEL) *.orig *.rej *.crlf ctags.c
		- $(DEL_TREE) deleted
		- $(DEL_TREE) obj
		- $(DEL_TREE) obj-spd

#
# Headers we would preprocess if we could.
#
..\src\config.h:	..\nt\$(CONFIG_H)
			$(CP) $** $@
..\src\paths.h:		..\nt\paths.h
			$(CP) $** $@

### DEPENDENCIES ###

EMACS_ROOT	= ..
SRC		= .

$(BLD)\b2m.obj : \
	$(SRC)\b2m.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h

$(BLD)\ctags.obj : \
	$(SRC)\ctags.c \
	$(EMACS_ROOT)\nt\inc\sys\param.h \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h \
	$(SRC)\ntlib.h \
	$(SRC)\getopt.h

$(BLD)\cvtmail.obj : \
	$(SRC)\cvtmail.c

$(BLD)\digest-doc.obj : \
	$(SRC)\digest-doc.c

$(BLD)\emacsclient.obj : \
	$(SRC)\emacsclient.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h

$(BLD)\emacsserver.obj : \
	$(SRC)\emacsserver.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h \
	$(EMACS_ROOT)\nt\inc\sys\file.h

$(BLD)\emacstool.obj : \
	$(SRC)\emacstool.c \
	$(EMACS_ROOT)\nt\inc\sys\file.h

$(BLD)\etags.obj : \
	$(SRC)\etags.c \
	$(EMACS_ROOT)\nt\inc\sys\param.h \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h \
	$(SRC)\ntlib.h \
	$(SRC)\getopt.h

$(BLD)\fakemail.obj : \
	$(SRC)\fakemail.c \
	$(SRC)\ntlib.h \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h \
	$(EMACS_ROOT)\nt\inc\pwd.h

$(BLD)\getdate.obj : \
	$(SRC)\getdate.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\src\config.h \
	$(MSTOOLS_SYS)\types.h

$(BLD)\getopt.obj : \
	$(SRC)\getopt.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\src\config.h \
	$(SRC)\ntlib.h \
	$(SRC)\getopt.h

$(BLD)\getopt1.obj : \
	$(SRC)\getopt1.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\src\config.h \
	$(SRC)\getopt.h

$(BLD)\hexl.obj : \
	$(SRC)\hexl.c

$(BLD)\leditcfns.obj : \
	$(SRC)\leditcfns.c

$(BLD)\make-docfile.obj : \
	$(SRC)\make-docfile.c \
	$(EMACS_ROOT)\src\config.h

$(BLD)\make-path.obj : \
	$(SRC)\make-path.c

$(BLD)\movemail.obj : \
	$(SRC)\movemail.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h \
	$(EMACS_ROOT)\nt\inc\sys\file.h \
	$(EMACS_ROOT)\lib-src\..\src\syswait.h \
	$(EMACS_ROOT)\nt\inc\pwd.h \
	$(SRC)\ntlib.h
	$(CC) $(CFLAGS) -DPROGRESS_DIALOG -DUSG -Fo$@ movemail.c

$(BLD)\progdlg.obj : \
	$(SRC)\progdlg.c \
	$(SRC)\progdlg.h

$(BLD)\progdlg.res: \
	$(SRC)\progdlg.rc
	$(RC) /fo$(BLD)\progdlg.res $(SRC)\progdlg.rc

$(BLD)\ntlib.obj : \
	$(SRC)\ntlib.c \
	$(SRC)\ntlib.h \
	$(EMACS_ROOT)\nt\inc\pwd.h

$(BLD)\pop.obj : \
	$(SRC)\pop.c \
	$(SRC)\pop.h \
	$(SRC)\ntlib.h
	$(CC) $(CFLAGS) -DPROGRESS_DIALOG -Fo$@ pop.c

$(BLD)\md5.obj : \
	$(SRC)\md5.c \
	$(SRC)\md5.h

$(BLD)\profile.obj : \
	$(SRC)\profile.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h \
	$(EMACS_ROOT)\lib-src\..\src\systime.h

$(BLD)\qsort.obj : \
	$(SRC)\qsort.c

$(BLD)\sorted-doc.obj : \
	$(SRC)\sorted-doc.c

$(BLD)\tcp.obj : \
	$(SRC)\tcp.c

$(BLD)\test-distrib.obj : \
	$(SRC)\test-distrib.c

$(BLD)\timer.obj : \
	$(SRC)\timer.c \
	$(EMACS_ROOT)\src\s\ms-w32.h \
	$(EMACS_ROOT)\src\m\intel386.h \
	$(EMACS_ROOT)\lib-src\..\src\config.h

$(BLD)\yow.obj : \
	$(SRC)\yow.c \
	$(EMACS_ROOT)\lib-src\..\src\paths.h
